exports.payrolltemplate = `<ENVELOPE>
<HEADER>
 <TALLYREQUEST>Import Data</TALLYREQUEST>
</HEADER>
<BODY>
 <IMPORTDATA>
  <REQUESTDESC>
   <REPORTNAME>All Masters</REPORTNAME>
   <STATICVARIABLES>
    <SVCURRENTCOMPANY></SVCURRENTCOMPANY>
   </STATICVARIABLES>
  </REQUESTDESC>
  <REQUESTDATA>
   <TALLYMESSAGE xmlns:UDF="TallyUDF">
    <VOUCHER REMOTEID="0bbd5096-36a4-4111-a30b-ffd161b46c91-00000531" VCHKEY="0bbd5096-36a4-4111-a30b-ffd161b46c91-0000aa41:00000018" VCHTYPE="Payroll" ACTION="Create" OBJVIEW="PaySlip Voucher View">
     <OLDAUDITENTRYIDS.LIST TYPE="Number">
      <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
     </OLDAUDITENTRYIDS.LIST>
     <DATE></DATE>
     <GUID>0bbd5096-36a4-4111-a30b-ffd161b46c91-00000531</GUID>
     <VOUCHERTYPENAME>Payroll</VOUCHERTYPENAME>
     <VOUCHERNUMBER></VOUCHERNUMBER>
     <PARTYLEDGERNAME></PARTYLEDGERNAME>
     <CSTFORMISSUETYPE/>
     <CSTFORMRECVTYPE/>
     <FBTPAYMENTTYPE>Default</FBTPAYMENTTYPE>
     <PERSISTEDVIEW>PaySlip Voucher View</PERSISTEDVIEW>
     <VCHGSTCLASS/>
     <DIFFACTUALQTY>No</DIFFACTUALQTY>
     <ISMSTFROMSYNC>No</ISMSTFROMSYNC>
     <ASORIGINAL>No</ASORIGINAL>
     <AUDITED>No</AUDITED>
     <FORJOBCOSTING>No</FORJOBCOSTING>
     <ISOPTIONAL>No</ISOPTIONAL>
     <EFFECTIVEDATE></EFFECTIVEDATE>
     <USEFOREXCISE>No</USEFOREXCISE>
     <ISFORJOBWORKIN>No</ISFORJOBWORKIN>
     <ALLOWCONSUMPTION>No</ALLOWCONSUMPTION>
     <USEFORINTEREST>No</USEFORINTEREST>
     <USEFORGAINLOSS>No</USEFORGAINLOSS>
     <USEFORGODOWNTRANSFER>No</USEFORGODOWNTRANSFER>
     <USEFORCOMPOUND>No</USEFORCOMPOUND>
     <USEFORSERVICETAX>No</USEFORSERVICETAX>
     <ISEXCISEVOUCHER>No</ISEXCISEVOUCHER>
     <EXCISETAXOVERRIDE>No</EXCISETAXOVERRIDE>
     <USEFORTAXUNITTRANSFER>No</USEFORTAXUNITTRANSFER>
     <IGNOREPOSVALIDATION>No</IGNOREPOSVALIDATION>
     <EXCISEOPENING>No</EXCISEOPENING>
     <USEFORFINALPRODUCTION>No</USEFORFINALPRODUCTION>
     <ISTDSOVERRIDDEN>No</ISTDSOVERRIDDEN>
     <ISTCSOVERRIDDEN>No</ISTCSOVERRIDDEN>
     <ISTDSTCSCASHVCH>No</ISTDSTCSCASHVCH>
     <INCLUDEADVPYMTVCH>No</INCLUDEADVPYMTVCH>
     <ISSUBWORKSCONTRACT>No</ISSUBWORKSCONTRACT>
     <ISVATOVERRIDDEN>No</ISVATOVERRIDDEN>
     <IGNOREORIGVCHDATE>No</IGNOREORIGVCHDATE>
     <ISVATPAIDATCUSTOMS>No</ISVATPAIDATCUSTOMS>
     <ISDECLAREDTOCUSTOMS>No</ISDECLAREDTOCUSTOMS>
     <ISSERVICETAXOVERRIDDEN>No</ISSERVICETAXOVERRIDDEN>
     <ISISDVOUCHER>No</ISISDVOUCHER>
     <ISEXCISEOVERRIDDEN>No</ISEXCISEOVERRIDDEN>
     <ISEXCISESUPPLYVCH>No</ISEXCISESUPPLYVCH>
     <ISGSTOVERRIDDEN>No</ISGSTOVERRIDDEN>
     <GSTNOTEXPORTED>No</GSTNOTEXPORTED>
     <IGNOREGSTINVALIDATION>No</IGNOREGSTINVALIDATION>
     <ISVATPRINCIPALACCOUNT>No</ISVATPRINCIPALACCOUNT>
     <ISBOENOTAPPLICABLE>No</ISBOENOTAPPLICABLE>
     <ISSHIPPINGWITHINSTATE>No</ISSHIPPINGWITHINSTATE>
     <ISOVERSEASTOURISTTRANS>No</ISOVERSEASTOURISTTRANS>
     <ISDESIGNATEDZONEPARTY>No</ISDESIGNATEDZONEPARTY>
     <ISCANCELLED>No</ISCANCELLED>
     <HASCASHFLOW>Yes</HASCASHFLOW>
     <ISPOSTDATED>No</ISPOSTDATED>
     <USETRACKINGNUMBER>No</USETRACKINGNUMBER>
     <ISINVOICE>No</ISINVOICE>
     <MFGJOURNAL>No</MFGJOURNAL>
     <HASDISCOUNTS>No</HASDISCOUNTS>
     <ASPAYSLIP>Yes</ASPAYSLIP>
     <ISCOSTCENTRE>No</ISCOSTCENTRE>
     <ISSTXNONREALIZEDVCH>No</ISSTXNONREALIZEDVCH>
     <ISEXCISEMANUFACTURERON>No</ISEXCISEMANUFACTURERON>
     <ISBLANKCHEQUE>No</ISBLANKCHEQUE>
     <ISVOID>No</ISVOID>
     <ISONHOLD>No</ISONHOLD>
     <ORDERLINESTATUS>No</ORDERLINESTATUS>
     <VATISAGNSTCANCSALES>No</VATISAGNSTCANCSALES>
     <VATISPURCEXEMPTED>No</VATISPURCEXEMPTED>
     <ISVATRESTAXINVOICE>No</ISVATRESTAXINVOICE>
     <VATISASSESABLECALCVCH>No</VATISASSESABLECALCVCH>
     <ISVATDUTYPAID>Yes</ISVATDUTYPAID>
     <ISDELIVERYSAMEASCONSIGNEE>No</ISDELIVERYSAMEASCONSIGNEE>
     <ISDISPATCHSAMEASCONSIGNOR>No</ISDISPATCHSAMEASCONSIGNOR>
     <ISDELETED>No</ISDELETED>
     <CHANGEVCHMODE>No</CHANGEVCHMODE>
     <ALTERID></ALTERID>
     <MASTERID></MASTERID>
     <VOUCHERKEY>187196149596184</VOUCHERKEY>
     <EXCLUDEDTAXATIONS.LIST>      </EXCLUDEDTAXATIONS.LIST>
     <OLDAUDITENTRIES.LIST>      </OLDAUDITENTRIES.LIST>
     <ACCOUNTAUDITENTRIES.LIST>      </ACCOUNTAUDITENTRIES.LIST>
     <AUDITENTRIES.LIST>      </AUDITENTRIES.LIST>
     <DUTYHEADDETAILS.LIST>      </DUTYHEADDETAILS.LIST>
     <SUPPLEMENTARYDUTYHEADDETAILS.LIST>      </SUPPLEMENTARYDUTYHEADDETAILS.LIST>
     <EWAYBILLDETAILS.LIST>      </EWAYBILLDETAILS.LIST>
     <INVOICEDELNOTES.LIST>      </INVOICEDELNOTES.LIST>
     <INVOICEORDERLIST.LIST>      </INVOICEORDERLIST.LIST>
     <INVOICEINDENTLIST.LIST>      </INVOICEINDENTLIST.LIST>
     <ATTENDANCEENTRIES.LIST>      </ATTENDANCEENTRIES.LIST>
     <ORIGINVOICEDETAILS.LIST>      </ORIGINVOICEDETAILS.LIST>
     <INVOICEEXPORTLIST.LIST>      </INVOICEEXPORTLIST.LIST>
     <LEDGERENTRIES.LIST>
      <OLDAUDITENTRYIDS.LIST TYPE="Number">
       <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
      </OLDAUDITENTRYIDS.LIST>
      <LEDGERNAME></LEDGERNAME>
      <GSTCLASS/>
      <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
      <LEDGERFROMITEM>No</LEDGERFROMITEM>
      <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
      <ISPARTYLEDGER>Yes</ISPARTYLEDGER>
      <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
      <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
      <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
      <AMOUNT></AMOUNT>
      <SERVICETAXDETAILS.LIST>       </SERVICETAXDETAILS.LIST>
      <BANKALLOCATIONS.LIST>       </BANKALLOCATIONS.LIST>
      <BILLALLOCATIONS.LIST>       </BILLALLOCATIONS.LIST>
      <INTERESTCOLLECTION.LIST>       </INTERESTCOLLECTION.LIST>
      <OLDAUDITENTRIES.LIST>       </OLDAUDITENTRIES.LIST>
      <ACCOUNTAUDITENTRIES.LIST>       </ACCOUNTAUDITENTRIES.LIST>
      <AUDITENTRIES.LIST>       </AUDITENTRIES.LIST>
      <INPUTCRALLOCS.LIST>       </INPUTCRALLOCS.LIST>
      <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
      <EXCISEDUTYHEADDETAILS.LIST>       </EXCISEDUTYHEADDETAILS.LIST>
      <RATEDETAILS.LIST>       </RATEDETAILS.LIST>
      <SUMMARYALLOCS.LIST>       </SUMMARYALLOCS.LIST>
      <STPYMTDETAILS.LIST>       </STPYMTDETAILS.LIST>
      <EXCISEPAYMENTALLOCATIONS.LIST>       </EXCISEPAYMENTALLOCATIONS.LIST>
      <TAXBILLALLOCATIONS.LIST>       </TAXBILLALLOCATIONS.LIST>
      <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
      <TDSEXPENSEALLOCATIONS.LIST>       </TDSEXPENSEALLOCATIONS.LIST>
      <VATSTATUTORYDETAILS.LIST>       </VATSTATUTORYDETAILS.LIST>
      <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
      <INVOICEWISEDETAILS.LIST>       </INVOICEWISEDETAILS.LIST>
      <VATITCDETAILS.LIST>       </VATITCDETAILS.LIST>
      <ADVANCETAXDETAILS.LIST>       </ADVANCETAXDETAILS.LIST>
     </LEDGERENTRIES.LIST>
     <CATEGORYENTRY.LIST>
      <CATEGORY></CATEGORY>
      <EMPLOYEEENTRIES.LIST>
       <EMPLOYEENAME></EMPLOYEENAME>
       <EMPLOYEESORTORDER> 1</EMPLOYEESORTORDER>
       <AMOUNT></AMOUNT>
       <PAYHEADALLOCATIONS.LIST>
        <PAYHEADNAME></PAYHEADNAME>
        <ISDEEMEDPOSITIVE></ISDEEMEDPOSITIVE>
        <PAYHEADSORTORDER></PAYHEADSORTORDER>
        <AMOUNT></AMOUNT>
       </PAYHEADALLOCATIONS.LIST>
      </EMPLOYEEENTRIES.LIST>
     </CATEGORYENTRY.LIST>
     <PAYROLLMODEOFPAYMENT.LIST>      </PAYROLLMODEOFPAYMENT.LIST>
     <ATTDRECORDS.LIST>      </ATTDRECORDS.LIST>
     <GSTEWAYCONSIGNORADDRESS.LIST>      </GSTEWAYCONSIGNORADDRESS.LIST>
     <GSTEWAYCONSIGNEEADDRESS.LIST>      </GSTEWAYCONSIGNEEADDRESS.LIST>
     <TEMPGSTRATEDETAILS.LIST>      </TEMPGSTRATEDETAILS.LIST>
    </VOUCHER>
   </TALLYMESSAGE>
   <TALLYMESSAGE xmlns:UDF="TallyUDF">
    <COMPANY>
     <REMOTECMPINFO.LIST MERGE="Yes">
      <NAME>0bbd5096-36a4-4111-a30b-ffd161b46c91</NAME>
      <REMOTECMPNAME>Main</REMOTECMPNAME>
      <REMOTECMPSTATE>Tamil Nadu</REMOTECMPSTATE>
     </REMOTECMPINFO.LIST>
    </COMPANY>
   </TALLYMESSAGE>
  </REQUESTDATA>
 </IMPORTDATA>
</BODY>
</ENVELOPE>`