var payrolltallytemplateall = {
    "ENVELOPE": {
    "HEADER": {
    "TALLYREQUEST": "Import Data"
    },
    "BODY": {
    "IMPORTDATA": {
    "REQUESTDESC": {
    "REPORTNAME": "All Masters",
    "STATICVARIABLES": {
    "SVCURRENTCOMPANY": ""
    }
    },
    "REQUESTDATA": {
    "TALLYMESSAGE": [
    {
    "VOUCHER": {
    "OLDAUDITENTRYIDS.LIST": [{
            "OLDAUDITENTRYIDS": "-1",
            "_TYPE": "Number"
    }],
    "DATE": "",
    "GUID": "0bbd5096-36a4-4111-a30b-ffd161b46c91-00000531",
    "VOUCHERTYPENAME": "Payroll",
    "VOUCHERNUMBER": "",
    "PARTYLEDGERNAME": "",
    "CSTFORMISSUETYPE": "",
    "CSTFORMRECVTYPE": "",
    "FBTPAYMENTTYPE": "Default",
    "PERSISTEDVIEW": "PaySlip Voucher View",
    "VCHGSTCLASS": "",
    "DIFFACTUALQTY": "No",
    "ISMSTFROMSYNC": "No",
    "ASORIGINAL": "No",
    "AUDITED": "No",
    "FORJOBCOSTING": "No",
    "ISOPTIONAL": "No",
    "EFFECTIVEDATE": "",
    "USEFOREXCISE": "No",
    "ISFORJOBWORKIN": "No",
    "ALLOWCONSUMPTION": "No",
    "USEFORINTEREST": "No",
    "USEFORGAINLOSS": "No",
    "USEFORGODOWNTRANSFER": "No",
    "USEFORCOMPOUND": "No",
    "USEFORSERVICETAX": "No",
    "ISEXCISEVOUCHER": "No",
    "EXCISETAXOVERRIDE": "No",
    "USEFORTAXUNITTRANSFER": "No",
    "IGNOREPOSVALIDATION": "No",
    "EXCISEOPENING": "No",
    "USEFORFINALPRODUCTION": "No",
    "ISTDSOVERRIDDEN": "No",
    "ISTCSOVERRIDDEN": "No",
    "ISTDSTCSCASHVCH": "No",
    "INCLUDEADVPYMTVCH": "No",
    "ISSUBWORKSCONTRACT": "No",
    "ISVATOVERRIDDEN": "No",
    "IGNOREORIGVCHDATE": "No",
    "ISVATPAIDATCUSTOMS": "No",
    "ISDECLAREDTOCUSTOMS": "No",
    "ISSERVICETAXOVERRIDDEN": "No",
    "ISISDVOUCHER": "No",
    "ISEXCISEOVERRIDDEN": "No",
    "ISEXCISESUPPLYVCH": "No",
    "ISGSTOVERRIDDEN": "No",
    "GSTNOTEXPORTED": "No",
    "IGNOREGSTINVALIDATION": "No",
    "ISVATPRINCIPALACCOUNT": "No",
    "ISBOENOTAPPLICABLE": "No",
    "ISSHIPPINGWITHINSTATE": "No",
    "ISOVERSEASTOURISTTRANS": "No",
    "ISDESIGNATEDZONEPARTY": "No",
    "ISCANCELLED": "No",
    "HASCASHFLOW": "Yes",
    "ISPOSTDATED": "No",
    "USETRACKINGNUMBER": "No",
    "ISINVOICE": "No",
    "MFGJOURNAL": "No",
    "HASDISCOUNTS": "No",
    "ASPAYSLIP": "Yes",
    "ISCOSTCENTRE": "No",
    "ISSTXNONREALIZEDVCH": "No",
    "ISEXCISEMANUFACTURERON": "No",
    "ISBLANKCHEQUE": "No",
    "ISVOID": "No",
    "ISONHOLD": "No",
    "ORDERLINESTATUS": "No",
    "VATISAGNSTCANCSALES": "No",
    "VATISPURCEXEMPTED": "No",
    "ISVATRESTAXINVOICE": "No",
    "VATISASSESABLECALCVCH": "No",
    "ISVATDUTYPAID": "Yes",
    "ISDELIVERYSAMEASCONSIGNEE": "No",
    "ISDISPATCHSAMEASCONSIGNOR": "No",
    "ISDELETED": "No",
    "CHANGEVCHMODE": "No",
    "ALTERID": "",
    "MASTERID": "",
    "VOUCHERKEY": "187196149596184",
    "EXCLUDEDTAXATIONS.LIST":[],
    "OLDAUDITENTRIES.LIST": [],
    "ACCOUNTAUDITENTRIES.LIST":[],
    "AUDITENTRIES.LIST":[],
    "DUTYHEADDETAILS.LIST":[],
    "SUPPLEMENTARYDUTYHEADDETAILS.LIST": [],
    "EWAYBILLDETAILS.LIST":[],
    "INVOICEDELNOTES.LIST": [],
    "INVOICEORDERLIST.LIST": [],
    "INVOICEINDENTLIST.LIST":[],
    "ATTENDANCEENTRIES.LIST": [],
    "ORIGINVOICEDETAILS.LIST": [],
    "INVOICEEXPORTLIST.LIST": [],
    "LEDGERENTRIES.LIST":[],
    "CATEGORYENTRY.LIST":[
        {
            "CATEGORY": "",
            "EMPLOYEEENTRIES.LIST": []
            }

    ],
    "PAYROLLMODEOFPAYMENT.LIST": [],
    "ATTDRECORDS.LIST": [],
    "GSTEWAYCONSIGNORADDRESS.LIST": [],
    "GSTEWAYCONSIGNEEADDRESS.LIST": [],
    "TEMPGSTRATEDETAILS.LIST": [],
    "_REMOTEID": "",
    "_VCHKEY": "0bbd5096-36a4-4111-a30b-ffd161b46c91-0000aa41:00000018",
    "_VCHTYPE": "Payroll",
    "_ACTION": "Create",
    "_OBJVIEW": "PaySlip Voucher View"
    },
    "_xmlns:UDF": "TallyUDF"
    }]
    }
    }
    }
    }
    }

module.exports = { payrolltallytemplateall };